/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/3DModels/hand.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF, OrthographicCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/hand.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.071, -64.03, -144.253]} rotation={[-0.415, -0.043, -0.019]} scale={0.559}>
          <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[18.199, -95.575, 16.796]} rotation={[-Math.PI, 0, -Math.PI]} scale={[2.027, 2.027, 1.396]} />
          <mesh geometry={nodes['hand-3'].geometry} material={nodes['hand-3'].material} position={[23.998, -11.39, 3.544]} rotation={[-Math.PI, 0, -Math.PI]} scale={1.549} />
        </group>
        <directionalLight intensity={0.7} decay={2} rotation={[-0.506, 0.629, 0.756]} />
        <OrthographicCamera makeDefault={false} far={100000} near={0} position={[19.935, 0.644, 934.283]} />
      </group>
    </group>
  )
}

useGLTF.preload('/hand.gltf')
